# Generated by Django 5.0.1 on 2025-03-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0012_alter_child_age_alter_child_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_status', models.CharField(max_length=255)),
                ('medical_status_history', models.TextField()),
                ('disability_status', models.CharField(max_length=255)),
                ('disability_status_history', models.TextField()),
                ('allergies_history', models.TextField()),
                ('allergies_conditions', models.ManyToManyField(blank=True, to='msys42app.allergycondition')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msys42app.child')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('immunization_given', models.CharField(max_length=255)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='msys42app.medicalhistory')),
            ],
        ),
    ]
