# Generated by Django 5.0.2 on 2025-04-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0017_alter_annualmedicalcheck_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msys42app.child'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='fm_middlename',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
