# Generated by Django 5.2 on 2025-05-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0002_alter_annualmedicalcheck_hemoglobin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
                ('grade', models.CharField(blank=True, choices=[('Preparatory', 'Preparatory'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('NE', 'Not Evaluated'), ('Higher Education', 'Higher Education')], max_length=25, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msys42app.child')),
            ],
            options={
                'db_table': 'spc_ed',
            },
        ),
    ]
