# Generated by Django 5.2 on 2025-05-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0003_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiciansexam',
            name='grade',
        ),
    ]
