# Generated by Django 5.2 on 2025-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0004_remove_physiciansexam_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymedicalrecord',
            name='bp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
