# Generated by Django 5.2 on 2025-05-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0004_remove_familymedicalrecord_bmi_and_more'),
        ('msys42app', '0004_remove_physiciansexam_grade'),
    ]

    operations = [
    ]
