# Generated by Django 5.2 on 2025-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0005_merge_20250507_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiciansexam',
            name='grade',
            field=models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2),
        ),
    ]
