# Generated by Django 5.2 on 2025-05-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0008_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiciansexam',
            name='grade',
        ),
    ]
