# Generated by Django 5.2 on 2025-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0009_remove_physiciansexam_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='immunization_given',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies_history',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='dis_history',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='med_history',
            field=models.CharField(max_length=255),
        ),
    ]
