# Generated by Django 5.2 on 2025-05-08 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0010_alter_immunization_immunization_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiciansexam',
            name='other',
        ),
        migrations.RemoveField(
            model_name='physiciansexam',
            name='other_label',
        ),
        migrations.CreateModel(
            name='PhysiciansExamOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('condition', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('attribute', models.CharField(default='other', max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msys42app.child')),
            ],
            options={
                'db_table': 'phys_exam_other',
            },
        ),
    ]
