# Generated by Django 5.2 on 2025-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0011_remove_physiciansexam_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
