# Generated by Django 5.2 on 2025-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0005_remove_familymedicalrecord_bmi_and_more'),
        ('msys42app', '0012_alter_familymember_first_name'),
    ]

    operations = [
    ]
