# Generated by Django 5.2 on 2025-10-16 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0013_merge_20250509_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='spc_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]{3,4}\\d{4}$')]),
        ),
    ]
