# Generated by Django 5.0.1 on 2025-03-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0013_allergycondition_medicalhistory_immunization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualMedicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hemoglobin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('condition', models.TextField()),
                ('notes', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_medical_checks', to='msys42app.child')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhysiciansExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025)),
                ('grade', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('height', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('weight', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('bp', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('vision_right', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('vision_left', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('hearing_right', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('hearing_left', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('eyes', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('ears', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('nose', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('throat', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('teeth', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('heart', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('lungs', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('abdomen', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('nervous_system', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('skin', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('nutrition', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('other', models.CharField(choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2)),
                ('other_label', models.CharField(default='other', max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msys42app.child')),
            ],
        ),
    ]
