# Generated by Django 5.0.1 on 2025-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0014_annualmedicalcheck_physiciansexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualmedicalcheck',
            name='age',
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
