# Generated by Django 5.0.1 on 2025-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0015_remove_annualmedicalcheck_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='other_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
