# Generated by Django 5.0.2 on 2025-04-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0016_medicalhistory_other_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_lastname', models.CharField(max_length=25)),
                ('fm_firstname', models.CharField(max_length=25)),
                ('fm_middlename', models.CharField(max_length=25)),
                ('fm_relationship', models.CharField(max_length=25)),
                ('fm_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msys42app.child')),
            ],
        ),
    ]
