# Generated by Django 5.0.2 on 2025-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0019_familymedicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymedicalrecord',
            name='bmi',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='familymedicalrecord',
            name='bp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='familymedicalrecord',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='familymedicalrecord',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
