# Generated by Django 5.0.2 on 2025-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0020_familymedicalrecord_bmi_alter_familymedicalrecord_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymedicalrecord',
            name='bmi',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
