# Generated by Django 5.2 on 2025-04-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0022_alter_familymedicalrecord_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymedicalrecord',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
