# Generated by Django 5.2 on 2025-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0023_alter_familymedicalrecord_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualmedicalcheck',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='physiciansexam',
            name='other',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('A', 'A'), ('C', 'C'), ('R', 'R'), ('NE', 'NE')], default='NE', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='physiciansexam',
            name='other_label',
            field=models.CharField(blank=True, default='other', max_length=20, null=True),
        ),
    ]
